spring:
  security:
    oauth2:
      client:
        registration:
          my-oauth2-client:
            provider: keycloak
            client-id: read-journal
            client-secret: T8fhv3RsTFsB3IdD4ur6kCvOL3nFTZqS
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope: openid,profile
        provider:
          my-auth-server:
            issuer-uri: http://localhost:8181/realms/Journal